# Generated by Django 3.1.1 on 2020-10-14 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funder', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('TVSTP', 'TVSTP'), ('CDP', 'CDP'), ('APB', 'APB')], max_length=50)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Programmes', 'Programmes'), ('Administration', 'Admininstration')], max_length=50)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('USD Cash', 'USD Cash'), ('ZWL Cash', 'ZWL Cash'), ('USD Bank Transfer', 'USD Bank Transfer'), ('ZWL Bank Transfer', 'ZWL Bank Transfer')], default='ZWL Bank Transfer', max_length=30)),
                ('payee', models.CharField(max_length=255)),
                ('payee_details', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('justification_for_cash_payment', models.CharField(blank=True, max_length=255, null=True)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Recommended', 'Recommended'), ('Authorised', 'Authorised'), ('Processed', 'Processed'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], default='Pending', max_length=30)),
                ('reason_for_rejection', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('quotation', models.FileField(blank=True, default=None, null=True, storage='media/attachments', upload_to='')),
                ('authorized_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.manager')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.budget')),
                ('processed_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.financeofficer')),
                ('recommended_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.hod')),
                ('requested_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Liquidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_requested', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('process_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('reason_for_rejection_by_Finance', models.TextField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processed', 'Processed'), ('Rejected', 'Rejected'), ('Closed', 'Closed')], default='Pending', max_length=30)),
                ('receipts', models.FileField(blank=True, default=None, null=True, storage='media/attachments', upload_to='')),
                ('comments', models.TextField(blank=True, null=True)),
                ('compiled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.financeofficer')),
                ('requisition', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='expenses.requisition')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=None, max_length=50)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('total_allocation', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('budget', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='expenses.budget')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetedExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_line', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.budgetline')),
                ('requisition', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.requisition')),
            ],
        ),
        migrations.CreateModel(
            name='ActualExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('budget_line', models.ForeignKey(blank=True, default='Select', null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.budgetline')),
                ('liquidation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.liquidation')),
            ],
        ),
    ]
