# Generated by Django 3.1.1 on 2020-10-14 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20201014_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='authorized_by',
            field=models.ForeignKey(blank=True, default='Manager', null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.manager'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='processed_by',
            field=models.ForeignKey(blank=True, default='Chief FinanceOfficer', null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.financeofficer'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='recommended_by',
            field=models.ForeignKey(blank=True, default='Coordinator', null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.hod'),
        ),
    ]
