# Generated by Django 3.1.1 on 2020-10-14 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20201014_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='authorized_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.manager'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='processed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.financeofficer'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='recommended_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.hod'),
        ),
    ]
