# Generated by Django 3.1.1 on 2020-10-15 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_auto_20201014_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualexpense',
            name='budget_line',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.budgetline'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Recommended', 'Recommended'), ('Authorised', 'Authorised'), ('Processed', 'Processed'), ('Rejected', 'Rejected'), ('Paid', 'Paid'), ('Confirmed', 'Confirmed')], default='Pending', max_length=30),
        ),
    ]
