# Generated by Django 3.1.1 on 2020-10-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_auto_20201015_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualexpense',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
