# Generated by Django 3.1.1 on 2020-10-16 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0006_auto_20201015_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='funder',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='budgetedexpense',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='financeofficer',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hod',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manager',
            name='department',
            field=models.CharField(blank=True, choices=[('Programmes', 'Programmes'), ('Administration', 'Admininstration')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.budget'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='date_requested',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='payee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='payee_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requested_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Recommended', 'Recommended'), ('Authorised', 'Authorised'), ('Processed', 'Processed'), ('Rejected', 'Rejected'), ('Paid', 'Paid'), ('Confirmed', 'Confirmed')], default='Pending', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
    ]
