# Generated by Django 3.1.1 on 2020-10-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_auto_20201016_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualexpense',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetedexpense',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
