# Generated by Django 3.1.1 on 2020-10-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_progressindicator_official'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressindicator',
            name='task',
        ),
    ]
