# Generated by Django 3.1.1 on 2020-10-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_progressindicator_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressindicator',
            name='current_date',
        ),
        migrations.AddField(
            model_name='progressindicator',
            name='date_recorded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
